name: continauth
channels:
  - defaults
dependencies:
  - python=3.6
  # Development Tools (not necessarily needed)
  - conda-forge::black=19.3            # Code formatter
  - flake8=3.7.7
  - jedi=0.13.3
  - pydocstyle=3.0.0
  - pyflakes=2.1.1
  - pylint=2.3.1
  # Needed
  - pickle5
  - scikit-learn=0.21.2
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pandas=0.24.2
  - numexpr=2.6.9                     # Speed up some pandas ops
  - pip=19.1.1
  - scipy=1.2.1
  - keras=2.2.4
  - pytables=3.5.2                    # For hdf5 store
  - tqdm=4.32.1                       # Progress bar
  - conda-forge::dataclasses=0.6      # Backport of Python 3.7 DataClasses
  # For Jupyterlab
  - nodejs=11.14.0
  - conda-forge::ffmpeg=4.1.3         # Saving animated plots
  - seaborn=0.9.0
  - jupyterlab=0.35.6
  - ipywidgets=7.4.2
  # Not available in conda repos
  - pip:
    - jupyterlab_code_formatter==0.2.1
  

